### PR TITLE
Update package versions

### PR DESCRIPTION
**Pull request by lewanni**
I just forgot to use the good symbols as before in package.json

### CODE REVIEW

**Comment by Romko775** [comment]
Okay, I will look into it when I will be free. For now can we go with this stuff that we have? Or you experiencing some issues?

**Comment by lewanni** [comment]
> Okay, I will look into it when I will be free. For now can we go with this stuff that we have? Or you experiencing some issues?

Hello Sir,
Although we upgrade the library version for Angular 13 thanks to my 1st pull request, I still have issues to install dependencies in my Angular 13 (not 13.0.0, but  13.x.x the latest) webapp with node 12.22.9 (I have to work with node 12.22.9).

Here my errors:

```shell
xxxxxxx@xxxxx-15-9560:~/git/my-project(master)$ rm node_modules package-lock.json -R && npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: my-project@0.0.0
npm ERR! Found: @angular/common@13.3.11
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"^13.3.11" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"~13.0.0" from moment-timezone-picker@5.0.0
npm ERR! node_modules/moment-timezone-picker
npm ERR!   moment-timezone-picker@"5.0.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/xxxxx/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/xxxxx/.npm/_logs/2022-06-09T12_39_50_839Z-debug.log
```

Of course, I would like to avoid to use  `--force, or --legacy-peer-deps` to fix my issue because in Angular 12 it works.

I don't really understand the errors above.
I even try to install Angular 13.0.0 and I still got the same kind of errors.
Honestly, I don't really know how works the compatibility between npm packages versions.
So I think I use bad symbols in the `package.json` in my 1st pull request.
That's why I suggest this second pull request.

Best regards.

**Comment by Romko775** [comment]
There is a dep as next
https://www.npmjs.com/package/@ng-select/ng-select

mostly my updates rely on this package updates, can you check if bumping ng-select will fix this?

**Comment by Romko775** [comment]
@lewanni Just checked the marks and 
`~version` “Approximately equivalent to version”, will update you to all future patch versions, without incrementing the minor version. ~1.2.3 will use releases from 1.2.3 to <1.3.0.
`^version` “Compatible with version”, will update you to all future minor/patch versions, without incrementing the major version. ^2.3.4 will use releases from 2.3.4 to <3.0.0.

So I don't see a point to change `^13.0.0` to `~13.0.0`

Also the ng-select version is good.

Imho I think that for now not all packages are prepared to ng13, maybe you should use `--legacy-peer-deps`

**Comment by lewanni** [comment]
> So I don't see a point to change ^13.0.0 to ~13.0.0

Me neither ^^
But I saw you use this kind of symbol, even in others libraries and maybe for npm it can maybe solve my issue xD

As I said, I shouldn't use `--legacy-peer-deps` or `--force` because it works very well for Angular 12 in version 4.0.0.

All dependencies you need are up to date and they should work with Angular 13.
So, now I don't really how to do more and maybe this is not a personal issue.

To reproduce my issue: just make `npm i moment-timezone-picker` on a Angular 13 webapp and using node 12.22.9

Anyway, you can close this pull request if you think is not necessary.

**Comment by lewanni** [comment]
My pull request should work with no impact.
You can test it by installing this [npm i xxx-test ](https://www.npmjs.com/package/woleet-quang-test) in a new angular 13 webapp.

I create this package just for testing and it fixes my current [issue](https://github.com/Romko775/ng-moment-timezone-picker/pull/75#issuecomment-1151104671) (of course I will delete it later)

**Comment by Romko775** [comment]
@lewanni Pushed with v5.0.1

**Comment by lewanni** [comment]
Thank you so much :)

**Pull request merged**
